### ISSUE TITLE
messages respNews function has an error

### ISSUE THREAD

**Issue by shellyxue** [ihaolin/wechat#1]
/**
     \* 被动回复微信服务器图文消息
     \* @param openId 用户openId
     \* @param articles 图片消息对象列表，长度小于10
     \* @return XML图文消息
     */
    public String respNews(String openId, List<Article> articles){
        ……
        checkArgument(articles.size() > 10, "articles length must < 10");
       ==》
        checkArgument(articles.size() < 10, "articles length must < 10");
        ……
    }

**Comment by ihaolin** [comment]
Thanks，it's fixed in **version 1.6.6**。
