### ISSUE TITLE
可以把这个功能加上

### ISSUE THREAD

**Issue by cjahv** [ihaolin/wechat#11]
https://api.weixin.qq.com/cgi-bin/message/custom/send 这个是发送客服消息，和下面的发送预览消息接口很像

https://api.weixin.qq.com/cgi-bin/message/mass/preview

**Comment by ihaolin** [comment]
http://mp.weixin.qq.com/wiki/11/c88c270ae8935291626538f9c64bd123.html#.E5.AE.A2.E6.9C.8D.E6.8E.A5.E5.8F.A3-.E5.8F.91.E6.B6.88.E6.81.AF

**Comment by cjahv** [comment]
对就是这个接口。可以加上吗？

**Comment by shenzhuan** [comment]
dev.properties 这个配置文件没有找到

**Comment by ihaolin** [comment]
在test/resources下创建一个就可以，这里包含了敏感信息，就没放进来

**Comment by shenzhuan** [comment]
你可以把参数设为空啊 但是东西得加上哦
