### ISSUE TITLE
组件内关于doPost的不良实现

### ISSUE THREAD

**Issue by zmapleshine** [ihaolin/wechat#13]
现有个多线程调用发送模板消息的功能，通过服务器监控发现在此情形下抛出java.net.BindException: Address already in use: connect

**Comment by ihaolin** [comment]
看这个错误，像是本地服务启动了多次，同一端口被占用，wechat只是一个客户端包，不会启动服务，排查下是不是环境问题。

**Comment by zmapleshine** [comment]
您好，并不会出现此问题在单个线程情况。 初步分析是由于每个线程的http请求结束后端口并没有完全被释放， 需等待操作系统中TIME_WAIT 在您的工具包里无法设置类似：httpmethod.setRequestHeader("Connection", "close");
这样的代码   决定在服务器的/etc/sysctl.conf文件，增加以下三行 ：
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
最后， 再次感谢作者的支持 !工具包很好用，此外，希望能更加完善微信接口，比如添加模板消息的接口（目前尚未添加，我自己已经临时采用继承Component抽象类的来实现）. thank u !

**Comment by ihaolin** [comment]
好的，感谢建议：

+ 应该不是请求头的问题，内部http请求，每次都会new一个URL，如图：
    
    <img width="467" alt="wx20170906-202356 2x" src="https://user-images.githubusercontent.com/8662695/30111750-7ff31028-9341-11e7-8281-dd770f5fdbe3.png">

+ 由于现在不负责这块项目，可能不是太方便升级调试。
