### ISSUE TITLE
castexception  location core.Messages

### ISSUE THREAD

**Issue by shellyxue** [ihaolin/wechat#2]
/**
     \* 群发消息:
     \*  1. 分组群发:【订阅号与服务号认证后均可用】
     \*  2. 按OpenId列表发: 订阅号不可用，服务号认证后可用
     \*  @see me.hao0.wechat.model.message.send.SendMessageScope
     \* @param accessToken accessToken
     \* @param msg 消息 
     \* @return 消息ID，或抛WechatException
     \* {errcode=0, errmsg=send job submission success, msg_id=402533248}，这个值没带L
     \* （Long）resp.get("msg_id") ，是错的
     */
    public Long send(String accessToken, SendMessage msg){
        ……
        return (Long)resp.get("msg_id");
        ===>
        return Long.parseLong(resp.get("msg_id").toString());
    }

here is the test

  public static void  main(String[] args){
        Map<String, Object> resp = new HashMap<String, Object>();
        resp.put("integer",2);
        resp.put("long",12L);
        System.out.print((Integer)resp.get("integer"));
        System.out.print((Long)resp.get("long"));
//        System.out.print((Long)resp.get("integer")); //case error
    }

**Comment by shellyxue** [comment]
谢谢作者，这么好个项目,回头有问题了多多指教哈

**Comment by shellyxue** [comment]
这个msg_id没超出Integer范围，可以采用Integer

**Comment by ihaolin** [comment]
谢谢提醒，该问题由于**jackson反序列化**转换时，我测试发送消息时返回的**消息ID**为，如**2549136382**，jackson会自动转换，如果未超过int值范围，则序列化为Integer，超过int范围则用Long型，**1.6.7版本**中将统一为Long型。
