### ISSUE TITLE
getUserInfo好像不能用

### ISSUE THREAD

**Issue by cjahv** [ihaolin/wechat#9]
https://api.weixin.qq.com/sns/userinfo(user.userInfo)需要的access_token参数不是全局的access_token
是https://api.weixin.qq.com/sns/oauth2/access_token(base.openId)接口返回的access_token,
但是这个接口把其他参数抛弃了

**Comment by ihaolin** [comment]
嗯这个接口，还没用过，都是通过getUser获取的，稍后修复下这个。

**Comment by ihaolin** [comment]
这个弄混了，之前获取用户openId就是走的[https://api.weixin.qq.com/sns/oauth2/access_token](https://api.weixin.qq.com/sns/oauth2/access_token)，当时只获取了openId，这个1.9.1修复了，通过用户授权后，获取用户信息需要走两步：

    AuthAccessToken token = Bases.authAccessToken(code);
    UserInfo userInfo = Users.getUserInfo(token);
